#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

# desc "same as 'bundle install --path vendor --without=production' "
# task :install do
# end

# desc "same as 'bundle update' "
# task :update do
# end

# desc "install the 'questionnaire' gem"
# task :gem do
# end