class CreateEmailTemplates < ActiveRecord::Migration
  def self.up
    create_table EmailTemplate.table_name, :force => true do |t|
      t.string  "name",    :limit => 1000, :null => false
      t.text    "content"
      t.boolean "enabled"
      t.string  "subject"
      t.timestamps
    end
    EmailTemplate.connection.insert("INSERT INTO `#{EmailTemplate.table_name}` (`id`,`name`,`content`,`enabled`,`subject`)
      VALUES
      	(1,'Staff Payment Request','Dear {{ staff_full_name }}:\r\n\r\n{{ applicant_full_name }} has just applied for an exciting STINT opportunity with Campus Crusade for Christ and has indicated you have agreed to pay the application fee.  If you could take a minute and indicate the account to use, we can continue with the application process.  The application materials will then be reviewed and a decision will be given as soon as possible.\r\n\r\nThe payment form is on our secure web site.  Just click on the link below to go directly to the payment form for {{ applicant_full_name }}.  The applicant\\\'s application will not processed until payment is made.  Thank you for your help in sending this laborer into the harvest!\r\n\r\nYou may contact the applicant by email at {{ applicant_email }} or by phone at {{ applicant_home_phone }}.\r\n\r\nFrom the link below, you can either indicate the account number to use for payment or indicate your unwillingness to pay for this application.  Either way, please follow the link and make a determination.\r\n\r\nThank you very much.\r\n\r\nSincerely,\r\nCampus Crusade for Christ\r\n\r\n<a href=\"{{ payment_request_url }}\">Click here to access payment form for {{ applicant_full_name }}</a>.\r\n\r\nIf the above link does not work.  Please use the following link.  The link should be all in one line, so if it is split up into more than one line, you may need to copy and paste the link into a web browser.\r\n\r\n{{ payment_request_url }}',NULL,'Application Payment Request for {{ applicant_full_name }}'),
      	(2,'Reference Invite','Dear {{ reference_full_name }},\n\n{{ applicant_full_name }} has just applied for an exciting internship opportunity with Campus Crusade for Christ and has suggested that we contact you as a reference. If you could take some time and fill out a recommendation for this applicant, we can continue with the application process.  The application materials will then be reviewed and a decision will be given as soon as possible.\n\nIn case you don\\\'t have time to finish the reference form in one sitting, we allow you to save and come back to it whenever it is convenient for you to finish.\n\nThe reference form is on our secure web site.  Just use the link below to go directly to the reference form for {{ applicant_full_name }}.  Your reference will be kept confidential, and the applicant will not be able to read the information you share with us.  The insight that you provide will be very helpful in determining a decision about this applicant\\\'s internship!\n\nYou may contact the applicant by email at {{ applicant_email }} or by phone at {{ applicant_home_phone }}.\n\nIf you would prefer not to participate, please notify the applicant yourself so that they can take you off of their reference list.  If you would prefer to fill out a paper reference form, please ask the applicant to provide you one.\n\nPlease do not forward this email to the applicant, so that they do not receive the link for editing their own reference form.\n\nThank you very much.\n\nSincerely,\nCampus Crusade for Christ\n\n\nPlease use the following link. The link should be all in one line, so if it is split up into more than one line, you may need to copy the entire address (including both/all of the lines) into your web browser\\\'s address bar.\n\n{{ reference_url }}\n\nYou do not have to fill out the entire form at one time.  After you start filling out the form, you may exit at any time and return later to finish.  Just use the same link to return to finishing the form.',NULL,'Reference Request for {{ applicant_full_name }}'),
      	(4,'Applicant Staff Payment Receipt','Dear {{ applicant_full_name }},\n\nA staff member has just paid for your application via account transfer.\n\nThank you very much.\n\nSincerely,\nCampus Crusade for Christ',NULL,'Application Payment Notification'),
      	(5,'Tool Owner Payment Confirmation','To whom it may concern:\n\nTake: {{ payment_amount }}\nFrom: {{ payment_account_no }}\nAuthorized by: {{ payment_auth_code }}\nPayment record ID: {{ payment_id }}\n\nSincerely,\nCampus Crusade for Christ',NULL,'Application Payment Notification'),
      	(6,'Payment Refusal','Dear {{ applicant_full_name }},\n\nThe staff member you requested payment from for your Application has just notified us of their refusal to pay.  Please contact them or make other payment arrangements.  You can log onto the system and pay via credit card or check/money order.\n\nSorry for the inconvenience...  Please remember your application will not be processed until the fee is paid.\n\nSincerely,\nCampus Crusade for Christ',NULL,'Application Payment Notification'),
      	(7,'Reference Notification to Applicant','Dear {{ applicant_full_name }}:\n\nThis email is to notify you that we have sent an email on your behalf to {{ reference_full_name }} inviting him or her to submit a reference for your participation in a  STINT or Internship.  The email was sent to: {{ reference_email }}.  If the email address is invalid or the message is returned for any reason, you will receive the returned email.  If this happens, 1) please login to your STINT/Internship application, 2) go to the References page, 3) correct the reference\\\'s email address, and 4) click the \\\'Send Email Invitation\\\' button.\n\nTo make any changes to your application form or to this reference, please click on this link: {{ application_url }}\n\nSincerely,\nCampus Crusade for Christ',NULL,'STINT/Internship Reference for {{ applicant_full_name }}'),
      	(8,'Reference Complete','Dear {{ applicant_full_name }}:\n\nA reference form filled out by {{ reference_full_name }} recommending you for a STINT/Internship has been completed and was submitted on {{ reference_submission_date }}.  You are now one step closer to finding out the decision about your internship application!   When a final decision is reached, we will let you know.  We trust that God will use this time of waiting as you continue to seek His will.\n\nSincerely,\nCampus Crusade for Christ',NULL,'STINT/Internship Reference Complete for {{ applicant_full_name }}'),
      	(9,'Reference Thank You','Dear {{ reference_full_name }}:\n\nThank you for completing the reference form for {{ applicant_full_name }}!  You are helping this applicant to make an eternal spiritual investment!  We thank you for giving of your limited time in order to give us insight about this applicant.\n\nSincerely,\nCampus Crusade for Christ',NULL,'Thank You for Completing an Internship Reference for {{ applicant_full_name }}'),
      	(10,'Credit Card Error','{{error}}',NULL,'Problem with STINT Application Credit Card Submission');")
    add_index EmailTemplate.table_name, :name
  end

  def self.down
    remove_index EmailTemplate.table_name, :name
    drop_table EmailTemplate.table_name
  end
end